name: OpenLangAI
options:
  bundleIdPrefix: com.AHTechnologies
configs:
  Debug: debug
  Release: release
schemes:
  OpenLangAI:
    build:
      targets:
        OpenLangAI: [run, test]
    test:
      targets:
        - OpenLangAITests
        - OpenAIClientKitTests
        - SecureStoreKitTests
targets:
  OpenLangAI:
    type: application
    platform: iOS
    deploymentTarget: "18.5"
    sources:
      - OpenLangAI
    dependencies:
      - target: AudioPipelineKit
      - target: OpenAIClientKit
      - target: SecureStoreKit
      - target: PersistenceKit
    infoPlist: OpenLangAI/Info.plist
  AudioPipelineKit:
    type: framework
    platform: iOS
    sources:
      - Packages/AudioPipelineKit/Sources
    settings:
      GENERATE_INFOPLIST_FILE: YES
  OpenAIClientKit:
    type: framework
    platform: iOS
    sources:
      - Packages/OpenAIClientKit/Sources
    dependencies:
      - target: SecureStoreKit
    settings:
      GENERATE_INFOPLIST_FILE: YES
  SecureStoreKit:
    type: framework
    platform: iOS
    sources:
      - Packages/SecureStoreKit/Sources
    settings:
      GENERATE_INFOPLIST_FILE: YES
  PersistenceKit:
    type: framework
    platform: iOS
    sources:
      - Packages/PersistenceKit/Sources
    resources:
      - Packages/PersistenceKit/Sources/PersistenceKit/OpenLangAI.xcdatamodeld
    settings:
      GENERATE_INFOPLIST_FILE: YES
  OpenLangAITests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.5"
    sources:
      - OpenLangAITests
    dependencies:
      - target: OpenLangAI
    settings:
      GENERATE_INFOPLIST_FILE: YES
  OpenAIClientKitTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.5"
    sources:
      - Packages/OpenAIClientKit/Tests/OpenAIClientKitTests
    dependencies:
      - target: OpenAIClientKit
      - target: SecureStoreKit
    settings:
      GENERATE_INFOPLIST_FILE: YES
  SecureStoreKitTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.5"
    sources:
      - Packages/SecureStoreKit/Tests/SecureStoreKitTests
    dependencies:
      - target: SecureStoreKit
    settings:
      GENERATE_INFOPLIST_FILE: YES
